spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/summerpiece;
    username: summerpiece
    password: summerpiece
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ""
    password: ""
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

